// Exports the design tokens as one machine-readable table: every CSS custom
// property in design/tokens/*.css, with its raw declaration and its resolved
// value, grouped by source file and theme context. The committed output,
// design/tokens.json, is the token contract the implementation side lints
// both platform themes against (design ⇄ impl seam, entries 001–004): token
// NAMES are append-only — renaming one is a breaking change for the
// conformance harness.
//
// Contexts: `tokens` is the top-level `:root` set (the light theme);
// `dark` is the `[data-theme="dark"]` override set; `reduced-motion` is
// what `@media (prefers-reduced-motion: reduce)` overrides. Resolution
// substitutes var() references (fallbacks honored) against the union of all
// files, overrides layered over light; a value that is not a var() chain
// (calc(), lists) resolves to the substituted string, not an evaluation.
//
// The repo-root design-tokens.json (the M3 colour contract both clients pin
// to, regenerated by `make tokens`) stays the colour source of truth;
// colors.css transcribes it, and this export carries the transcription —
// agreement between the two is design.md §2's existing discipline.
//
// Run from this directory, after nothing: node export-tokens.mjs
// (exit 1 when a var() reference resolves to nothing).

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const t0 = Date.now();
const here = dirname(fileURLToPath(import.meta.url));
const tokensDir = resolve(here, "..", "tokens");
const outPath = resolve(here, "..", "tokens.json");

const stripComments = (css) => css.replace(/\/\*[\s\S]*?\*\//g, "");

// Walks top-level blocks of a stylesheet: yields { selector, body } with
// nested braces kept inside body (an at-rule's body holds its own blocks).
function* blocks(css) {
  let i = 0;
  while (i < css.length) {
    const open = css.indexOf("{", i);
    if (open === -1) return;
    const selector = css.slice(i, open).trim();
    let depth = 1;
    let j = open + 1;
    while (j < css.length && depth > 0) {
      if (css[j] === "{") depth++;
      else if (css[j] === "}") depth--;
      j++;
    }
    yield { selector, body: css.slice(open + 1, j - 1) };
    i = j;
  }
}

const declRe = /(--[\w-]+)\s*:\s*([^;]+);/g;
const props = (body) => {
  const out = {};
  for (const m of body.matchAll(declRe)) out[m[1]] = m[2].trim().replace(/\s+/g, " ");
  return out;
};

// Per file: { light, dark, reduced } raw maps.
const perFile = new Map();
const files = readdirSync(tokensDir).filter((f) => f.endsWith(".css")).sort();
for (const f of files) {
  const css = stripComments(readFileSync(join(tokensDir, f), "utf8"));
  const light = {}, dark = {}, reduced = {};
  for (const b of blocks(css)) {
    if (b.selector === ":root") Object.assign(light, props(b.body));
    else if (b.selector.replace(/\s+/g, "") === '[data-theme="dark"]') Object.assign(dark, props(b.body));
    else if (/^@media[^{]*prefers-reduced-motion:\s*reduce/.test(b.selector)) Object.assign(reduced, props(b.body));
  }
  if (Object.keys(light).length + Object.keys(dark).length + Object.keys(reduced).length > 0)
    perFile.set(f, { light, dark, reduced });
}

const union = (ctx) => {
  const all = {};
  for (const { light } of perFile.values()) Object.assign(all, light);
  if (ctx !== "light") for (const maps of perFile.values()) Object.assign(all, maps[ctx]);
  return all;
};
const scopes = { light: union("light"), dark: union("dark"), reduced: union("reduced") };

const fails = [];
function resolveValue(value, scope, trail = []) {
  return value.replace(/var\(\s*(--[\w-]+)\s*(?:,\s*([^()]*(?:\([^()]*\)[^()]*)*))?\)/g, (whole, name, fallback) => {
    if (trail.includes(name)) {
      fails.push(`circular var() through ${name} (${trail.join(" -> ")})`);
      return whole;
    }
    const next = scopes[scope][name];
    if (next !== undefined) return resolveValue(next, scope, [...trail, name]);
    if (fallback !== undefined) return resolveValue(fallback.trim(), scope, trail);
    fails.push(`${name} resolves to nothing (referenced as ${whole})`);
    return whole;
  });
}

const out = { note: "Generated by design/_build/export-tokens.mjs from design/tokens/*.css — never edited by hand. Token names are an append-only contract (design ⇄ impl seam).", files: {} };
let count = 0;
for (const [f, maps] of perFile) {
  const entry = {};
  const emit = (rawMap, scope) => {
    const section = {};
    for (const name of Object.keys(rawMap).sort()) {
      section[name] = { raw: rawMap[name], resolved: resolveValue(rawMap[name], scope) };
      count++;
    }
    return section;
  };
  if (Object.keys(maps.light).length) entry.tokens = emit(maps.light, "light");
  if (Object.keys(maps.dark).length) entry.dark = emit(maps.dark, "dark");
  if (Object.keys(maps.reduced).length) entry["reduced-motion"] = emit(maps.reduced, "reduced");
  out.files[f] = entry;
}

if (fails.length) {
  for (const f of [...new Set(fails)]) console.error(`FAIL export-tokens: ${f}`);
  process.exit(1);
}
writeFileSync(outPath, JSON.stringify(out, null, 2) + "\n");
console.log(`export-tokens: ${count} tokens from ${perFile.size} files in ${Date.now() - t0} ms`);
